### PR TITLE
NYochum lab2

### PR DESCRIPTION
**Pull request by nsyochum**
@hmyin516

### CODE REVIEW

**Comment by hmyin516** [comment]
A few typos but they look good to me.

**Comment by nsyochum** [comment]
@AlexSchuy Ready for grading.

**Comment by nsyochum** [comment]
@AlexSchuy Combining in lab time and out of lab time, I spent about 5 hours on this lab

**Comment by AlexSchuy** [comment]
Hello, here are my comments for lab 2:

**General Thoughts**

I like the quotes of the problem text, but make sure it's somehow denoted that it is separate from the rest of your document. Often, people do this by emboldening the quoted text.

**Problem 1**

1.A) You should use the convolution operator here. Note that the plot is clearly incorrect, as the sum of probabilities for a probability distribution must sum to 1.

1.B) The idea is that the Poisson distribution describes the number of events in some time interval, where the events occur independently of each other with some constant average rate. Since the events are independent and constant in rate, it makes sense that we can add Poisson distributions over short intervals together to get a Poisson distribution for a longer interval. 

1.C) Explain what your 'P value' calculation is and why a lower value means the distribution is closer to a normal distribution. 

Since the average is just a sum divided by a scale factor, the shape of the average and sum are the same; you just need to scale the x-axis by a factor of 1/n and scale the pmf by a factor of n (to ensure the integral is still 1). 

1.D) Mention the values you chose in text, not in a comment in your code.

**Problem 2**

Way too many distributions in the plot; pick the minimum number that you think adequately illustrate the trend and no more. Also, plot a Gaussian overlaid with the Rayleigh plots to show that they become more Gaussian.

**Problem 3: Version 1**

State explicitly what values you chose in text, rather than in code.

**Problem 3: Version 2**

Fine.

**Problem 4**

Good.

**Pull request merged**
