### PR TITLE
NYochum lab1

### PR DESCRIPTION
**Pull request by nsyochum**
@hmyin516 Finished draft of lab.

### CODE REVIEW

**Review by hmyin516 — COMMENTED** [review]
LG = looks good
## A Little Stats:
1a: LG
  b,c .  maybe implement comments as markdown text for readability
   if we now integrate from -inf to 1, we are only going to half a standard deviation instead of a full deviation
I'm a little confused by this.
  d:  LG
2a: LG
  b:  maybe try adding more values for x and y axis for a bigger picture
3a:  radioactive typo. 
  b: LG
  c: LG
  d: LG
  4:  some formatting perhaps

## Non continuous distribution
1a:  LG
  b:  maybe make separate plots or fewer means. A bit jumbled. More values on x axis?
  c. LG
   d: LG

**Comment by nsyochum** [comment]
@AlexSchuy Ready for submission

**Comment by AlexSchuy** [comment]
Hi, here are my comments for lab 1:

**General Thoughts**

I've mentioned this to a few other people, but, while this is not a software engineering course, it can be nice to factor reused code into functions and to use loops where appropriate.

Also, please see my general comments in the slack channel regarding plotting technique.

**Problem 1**

1.A/B) Nice inclusion of the z-table and the shaded regions in the plots are excellent.

1.C/D) Fine.

**Problem 2** 

Good.

**Problem 3**

3.A/B/C/D) Excellent.

3.E) Note that the 'sigma' is always relative to the standard normal distribution, regardless of the presumed distribution of your measurement. Thus, you should use `stats.norm.ppf`, as you did in the first problem.

**Problem 4**

Lower probabilities are associated with **higher** 'sigma' values. Instead of printing a long list of values, it would be nicer to present a plot.

**Problem 5**

5.A/B) The plot is excellent. A minor note that you could further illustrate that the Poisson distribution approaches a Gaussian by plotting a Gaussian for comparison.

5.C/D/E) Very good.

**Comment by nsyochum** [comment]
@AlexSchuy combining in lab time and other time, I spent about 7 hours on this lab

**Pull request merged**
